/**
 * Builds the badge glyph set in src/badge-icons.ts from the installed lucide-react-native.
 *
 * Source:  node_modules/lucide-react-native (ISC). Attribution lives in NOTICE.md.
 * Offline by design — the version is whatever the lockfile resolved, so the artwork can
 * never drift from the `lucide-react` copy onli-admin renders.
 *
 * Run: bun scripts/build-badge-icons.ts
 */
const ICON_DIR = "node_modules/lucide-react-native/dist/esm/icons";

/**
 * Curated for achievements: one glyph per shipped badge, plus room for badges staff add
 * later. Biased to solid silhouettes that survive 16px inside a medal.
 */
const ICONS = [
  // shipped badges, in seed order
  "pen-line",
  "message-circle",
  "user-round-check",
  "wand-sparkles",
  "clapperboard",
  "palette",
  "code-xml",
  "briefcase",
  "bot",
  "files",
  "messages-square",
  "compass",
  "thumbs-up",
  "heart-handshake",
  "gem",
  "message-circle-more",
  "lightbulb",
  "flame",
  "calendar-check",
  "anchor",
  "mountain",
  "crown",
  "flag",
  "shield-check",
  // spares, so staff can add a badge without a deploy
  "award",
  "trophy",
  "star",
  "medal",
  "calendar-heart",
  "sparkles",
  "rocket",
  "zap",
  "target",
  "book-open",
  "graduation-cap",
  "bookmark",
  "handshake",
  "users",
  "eye",
  "mic",
  "camera",
  "music",
  "trending-up",
  "clock",
  "key",
  "puzzle",
  "wrench",
  "map",
];

/** The array literal lucide passes to createLucideIcon, sliced out by bracket depth. */
function nodeLiteral(src: string, name: string): string {
  const start = src.indexOf("createLucideIcon(");
  if (start < 0) throw new Error(`${name}: no createLucideIcon call`);
  const open = src.indexOf("[", start);
  if (open < 0) throw new Error(`${name}: no node array`);
  let depth = 0;
  let quote = "";
  for (let i = open; i < src.length; i++) {
    const c = src[i];
    if (quote) {
      if (c === "\\") i++;
      else if (c === quote) quote = "";
      continue;
    }
    if (c === '"' || c === "'") quote = c;
    else if (c === "[") depth++;
    else if (c === "]" && --depth === 0) return src.slice(open, i + 1);
  }
  throw new Error(`${name}: unterminated node array`);
}

const kebab = (k: string) => k.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

const out: string[] = [];
let bytes = 0;
for (const name of ICONS.slice().sort()) {
  const file = Bun.file(`${ICON_DIR}/${name}.js`);
  if (!(await file.exists())) throw new Error(`${name}: not in lucide-react-native`);
  const nodes = new Function(`return ${nodeLiteral(await file.text(), name)}`)() as [
    string,
    Record<string, string>,
  ][];
  const body = nodes
    .map(([tag, attrs]) => {
      const a = Object.entries(attrs)
        .filter(([k]) => k !== "key")
        .map(([k, v]) => `${kebab(k)}="${v}"`)
        .join(" ");
      return `<${tag} ${a}/>`;
    })
    .join("");
  const svg =
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" ' +
    'stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">' +
    `${body}</svg>`;
  bytes += svg.length;
  out.push(`  ${JSON.stringify(name)}: ${JSON.stringify(svg)},`);
}

const version = JSON.parse(
  await Bun.file("node_modules/lucide-react-native/package.json").text(),
).version;

await Bun.write(
  "src/badge-icons.ts",
  `// GENERATED by scripts/build-badge-icons.ts — do not edit by hand.
// Lucide ${version} (https://lucide.dev), ISC. See NOTICE.md.
//
// Inline strings rather than component imports: onli-app renders these through
// react-native-svg and onli-admin through an <img>, and one representation serves both.
// \`currentColor\` is left in place — SvgXml resolves it from its \`color\` prop, and the
// web medal substitutes a hex before building the data URI.

export const badgeIcons = {
${out.join("\n")}
} satisfies Record<string, string>;

export type BadgeIconName = keyof typeof badgeIcons;

export const badgeIconNames = Object.keys(badgeIcons) as BadgeIconName[];

/** Own keys only: 'constructor' and the other prototype names are not icons. */
export function isBadgeIcon(v: string | null | undefined): v is BadgeIconName {
  return !!v && Object.hasOwn(badgeIcons, v);
}

export function getBadgeIcon(name: string | null | undefined): string | undefined {
  return isBadgeIcon(name) ? badgeIcons[name] : undefined;
}
`,
);
console.log(
  `wrote src/badge-icons.ts — ${ICONS.length} icons, ${(bytes / 1024).toFixed(1)} KB of SVG`,
);

export {};
