/**
 * Vendors the channel icon set from Twemoji into src/channel-icons.ts.
 *
 * Source:  https://github.com/jdecked/twemoji (maintained fork of Twitter's Twemoji)
 * Version: pinned below — bump deliberately, never float to main
 * Licence: graphics are CC-BY 4.0. Attribution is required and lives in NOTICE.md;
 *          keep it there and visible if the app ever ships a credits screen.
 *
 * Run: bun scripts/fetch-channel-icons.ts
 */
const TWEMOJI_VERSION = "v17.0.3";

/** Curated for community channels, and biased to flat bold shapes that survive 18px. */
const ICONS: Record<string, string> = {
  "speech-balloon": "1f4ac",
  sparkles: "2728",
  question: "2753",
  "light-bulb": "1f4a1",
  rocket: "1f680",
  "graduation-cap": "1f393",
  books: "1f4da",
  megaphone: "1f4e3",
  calendar: "1f4c5",
  "waving-hand": "1f44b",
  briefcase: "1f4bc",
  laptop: "1f4bb",
  robot: "1f916",
  brain: "1f9e0",
  palette: "1f3a8",
  camera: "1f4f7",
  "clapper-board": "1f3ac",
  "musical-note": "1f3b5",
  memo: "1f4dd",
  "chart-increasing": "1f4c8",
  "money-bag": "1f4b0",
  wrench: "1f527",
  "puzzle-piece": "1f9e9",
  fire: "1f525",
  heart: "2764",
  star: "2b50",
  trophy: "1f3c6",
  compass: "1f9ed",
  coffee: "2615",
  globe: "1f30d",
  "high-voltage": "26a1",
  target: "1f3af",
  bookmark: "1f516",
  bell: "1f514",
  package: "1f4e6",
  gear: "2699",
};

const out: string[] = [];
let bytes = 0;
for (const [name, cp] of Object.entries(ICONS)) {
  const url = `https://raw.githubusercontent.com/jdecked/twemoji/${TWEMOJI_VERSION}/assets/svg/${cp}.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${name} (${cp}): HTTP ${res.status}`);
  const svg = (await res.text()).trim().replace(/\s+/g, " ");
  bytes += svg.length;
  out.push(`  ${JSON.stringify(name)}: ${JSON.stringify(svg)},`);
}

const header = `// GENERATED by scripts/fetch-channel-icons.ts — do not edit by hand.
// Twemoji ${TWEMOJI_VERSION} (https://github.com/jdecked/twemoji), graphics CC-BY 4.0. See NOTICE.md.
//
// Inline strings rather than files: react-native-svg's SvgXml wants a string, and onli-admin
// renders the same markup on the web, so one representation serves both with no asset pipeline.

export const channelIcons = {
${out.join("\n")}
} satisfies Record<string, string>;

export type ChannelIconName = keyof typeof channelIcons;

export const channelIconNames = Object.keys(channelIcons) as ChannelIconName[];

/** Own keys only: 'constructor' and the other prototype names are not icons. */
export function isChannelIcon(v: string | null | undefined): v is ChannelIconName {
  return !!v && Object.hasOwn(channelIcons, v);
}

export function getChannelIcon(name: string | null | undefined): string | undefined {
  return isChannelIcon(name) ? channelIcons[name] : undefined;
}
`;
await Bun.write("src/channel-icons.ts", header);
console.log(
  `wrote src/channel-icons.ts — ${Object.keys(ICONS).length} icons, ${(bytes / 1024).toFixed(1)} KB of SVG`,
);

export {};
