// GENERATED by scripts/build-rank-insignia.ts — do not edit by hand.
// Original artwork for Onli; no third-party licence applies.
//
// Keyed by the PERMANENT rung key from levels.thresholds, never the name: Admin -> Levels
// can rename a rung, and renaming must not silently swap or orphan its insignia. A rung
// staff add later has no mark and renders as text, which is the pre-insignia behaviour.
//
// Every mark is measured and scaled to one optical square by the script, so the six line up
// wherever they are rendered together, and every coordinate is ABSOLUTE — no element carries
// a transform, because a userSpaceOnUse gradient would otherwise resolve differently for a
// rotated leaf than for the stem beside it. Do not hand-edit.

export const rankInsignia = {
  beginner:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 19.88L12 10.32" fill="none" stroke="currentColor" stroke-width="3.24" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 10.93C17.17 11.36 20.59 7.82 20.14 2.5C14.82 2.24 11.4 5.79 12 10.93Z"/><path d="M12 10.93C12.6 5.79 9.18 2.24 3.86 2.5C3.41 7.82 6.83 11.36 12 10.93Z"/></svg>',
  enthusiast:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M4.4 15.8L12 8.2L19.6 15.8" fill="none" stroke="currentColor" stroke-width="3.8" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  practitioner:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2.5L20.52 5.83L20.52 12.39C20.52 16.8 16.9 20.03 12 21.5C7.1 20.03 3.48 16.8 3.48 12.39L3.48 5.83Z"/></svg>',
  specialist:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2.96L14.47 9.56L21.5 9.87L15.99 14.25L17.87 21.04L12 17.15L6.13 21.04L8.01 14.25L2.5 9.87L9.53 9.56Z"/></svg>',
  mentor:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M15.37 17.55A6.75 6.75 0 0 0 17.46 7.74" fill="none" stroke="currentColor" stroke-width="1.04" stroke-linecap="round"/><path d="M15.37 17.55C15.68 18.88 16.9 19.58 18.27 19.22C17.9 17.85 16.68 17.15 15.37 17.55Z"/><path d="M17.96 14.87C18.93 15.84 20.33 15.79 21.29 14.76C20.26 13.79 18.86 13.84 17.96 14.87Z"/><path d="M18.73 11.23C20.07 11.54 21.23 10.76 21.5 9.37C20.11 9.1 18.95 9.88 18.73 11.23Z"/><path d="M17.46 7.74C18.76 7.29 19.33 6.01 18.82 4.69C17.5 5.19 16.93 6.48 17.46 7.74Z"/><path d="M8.63 17.55A6.75 6.75 0 0 1 6.54 7.74" fill="none" stroke="currentColor" stroke-width="1.04" stroke-linecap="round"/><path d="M8.63 17.55C7.32 17.15 6.1 17.85 5.73 19.22C7.1 19.58 8.32 18.88 8.63 17.55Z"/><path d="M6.04 14.87C5.14 13.84 3.74 13.79 2.71 14.76C3.67 15.79 5.07 15.84 6.04 14.87Z"/><path d="M5.27 11.23C5.05 9.88 3.89 9.1 2.5 9.37C2.77 10.76 3.93 11.54 5.27 11.23Z"/><path d="M6.54 7.74C7.07 6.48 6.5 5.19 5.18 4.69C4.67 6.01 5.24 7.29 6.54 7.74Z"/><path d="M12 6.59L13.14 9.62L16.37 9.76L13.84 11.78L14.7 14.9L12 13.12L9.3 14.9L10.16 11.78L7.63 9.76L10.86 9.62Z"/></svg>',
  master:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M14.98 17.81A6.34 6.34 0 0 0 16.41 7.65" fill="none" stroke="currentColor" stroke-width="1.06" stroke-linecap="round"/><path d="M14.98 17.81C15.24 19.22 16.48 19.99 17.92 19.65C17.6 18.2 16.36 17.43 14.98 17.81Z"/><path d="M17.19 15.85C18.07 16.98 19.52 17.11 20.65 16.15C19.71 15 18.26 14.88 17.19 15.85Z"/><path d="M18.28 13.09C19.58 13.71 20.93 13.16 21.5 11.79C20.14 11.2 18.79 11.75 18.28 13.09Z"/><path d="M18 10.14C19.43 10.1 20.39 9 20.27 7.52C18.79 7.61 17.84 8.72 18 10.14Z"/><path d="M16.41 7.65C17.67 6.96 18.02 5.54 17.25 4.28C15.97 5.03 15.62 6.45 16.41 7.65Z"/><path d="M9.02 17.81A6.34 6.34 0 0 1 7.59 7.65" fill="none" stroke="currentColor" stroke-width="1.06" stroke-linecap="round"/><path d="M9.02 17.81C7.64 17.43 6.4 18.2 6.08 19.65C7.52 19.99 8.76 19.22 9.02 17.81Z"/><path d="M6.81 15.85C5.74 14.88 4.29 15 3.35 16.15C4.48 17.11 5.93 16.98 6.81 15.85Z"/><path d="M5.72 13.09C5.21 11.75 3.86 11.2 2.5 11.79C3.07 13.16 4.42 13.71 5.72 13.09Z"/><path d="M6 10.14C6.16 8.72 5.21 7.61 3.73 7.52C3.61 9 4.57 10.1 6 10.14Z"/><path d="M7.59 7.65C8.38 6.45 8.03 5.03 6.75 4.28C5.98 5.54 6.33 6.96 7.59 7.65Z"/><path d="M9.06 10.7L9.06 5.87L10.53 7.68L12 5.11L13.47 7.68L14.94 5.87L14.94 10.7Z"/></svg>',
} satisfies Record<string, string>;

export type RankKey = keyof typeof rankInsignia;

export const rankKeys = Object.keys(rankInsignia) as RankKey[];

/** Own keys only: 'constructor' and the other prototype names are not rungs. */
export function isRankKey(v: string | null | undefined): v is RankKey {
  return !!v && Object.hasOwn(rankInsignia, v);
}

export function getRankInsignia(key: string | null | undefined): string | undefined {
  return isRankKey(key) ? rankInsignia[key] : undefined;
}
